# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('p', models.CharField(max_length=100)),
            ],
        ),
    ]
