# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190115_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcar',
            old_name='is_delete',
            new_name='is_select',
        ),
    ]
